### ISSUE TITLE
no cdn replacement for ace editor

### ISSUE THREAD

**Issue by dimitrilongo** [reduxframework/redux-vendor-support#1]
hi,

first time i use this repo, but can't make it work with ace_editor, i try as a plugin or extension in both case, select2 works, because i have

``` javascript
/redux-admin/redux-extensions/extensions/vendor_support/vendor/select2/select2.css
```

in `<head>`

Regards
Dimitri

wp 4,2,2
redux embed 3.5.5.1
forced_dev_mode_off true
redux-vendor-support 3.0.0

**Comment by dimitrilongo** [comment]
ah i found, due to `forced_dev_mode_off` set to `true` when set to false, ace_editor is ok with local url.

**Comment by dovy** [comment]
?

**Comment by dovy** [comment]
Please explain.

**Comment by kprovance** [comment]
forced_dev_mode_off?  Really?  I'm regretting that decision already.

**Comment by dovy** [comment]
Haha.  ;)

**Comment by kprovance** [comment]
No, seriously.  Everyone will use, which negates the point of dev mode, and the issues pile up and we have to go back to telling these people to turn dev mode back on.  Waste of time.  :( :( :(

**Comment by dovy** [comment]
Heh, their choice. We will NOT provide support for anyone with that enabled.  ;)

**Comment by dimitrilongo** [comment]
euhh, i'm sorry guys, i don't understand i'm just one of your customer and bakers, just pointed something went wrong. 
concerning forced_dev_mode_off, i didn't sell on marketplace, my customer told me they get confused in wordpress admin , some users (very small companies) thought that redux was the designer of the website or maybe i really miss something with dev mode. Last day one my customer thought i will provide no support because he get confused in the wp admin, that not my point but ours. I had very few are dev that's the fact

**Comment by dovy** [comment]
So, do you have a question, or not? Is it working or not? Hehe. I'm a bit confused...

**Comment by dimitrilongo** [comment]
no , just the sensation you make fun of me. the issue is solved just disable forced_dev_mode_off.

**Comment by dovy** [comment]
Not at all! We're not making fun of you. It was @kprovance and I disagreeing about a decision I made.  ;)

It has NOTHING to do with you.  :)

Sorry if it seemed like that. That was not the intent.
