### ISSUE TITLE
Plugin doesn't work.

### ISSUE THREAD

**Issue by dinhtungdu** [reduxframework/redux-vendor-support#2]
Set use_cdn => false and tried both installation as plugin or extension. But it's doesn't work.

Got bellow warning and can't use select2, colorpicker..
The Redux Vendor Support plugin is either not installed or not activated and thus, some controls may not render properly. Please ensure the Redux Vendor Plugin is installed and activated..

**Comment by kprovance** [comment]
I'm sorry, but 'it doesn't work' tell me absolutely nothing.  No version information, no steps on how you installed, what you installed, how you did it.  I use the plugin all the time and it does in fact, work fine.

Let start with a support URL, please provide one:  https://docs.reduxframework.com/core/generating-a-support-hash/  Also, please be prepared to answer follow up question with some more detail.

**Comment by dinhtungdu** [comment]
I solved this by update latest version (3.5.5).

Thank you and so sorry for unclear question. Futher question will be clear and detail. I promise :).

But for more clea, I use Redux Framework v3.5.4.31 and Wordpress 4.2.2. I clone this repo, install then activate it as a plugin. I turn use_cdn flag to false. And the warning is still show up. 

_The Redux Vendor Support plugin is either not installed or not activated and thus, some controls may not render properly. Please ensure the Redux Vendor Plugin is installed and activated.._

**Comment by kprovance** [comment]
Yes, the 3.5.5+ version of Redux is required.

**Comment by zhang-chenglin** [comment]
Redux::setExtensions( $opt_name, dirname( __FILE__ ) . '/redux-framework/extension/redux-vendor-support.php' );

this isright？？
but tip：
The Vendor Support plugin (or extension) is either not installed or not activated and thus, some controls may not render properly. Please ensure that it is installed and activated.
