### ISSUE TITLE
Cannot activate the plugin.

### ISSUE THREAD

**Issue by IisusChristos** [reduxframework/redux-vendor-support#6]
After installing it on my wordpress website and trying to activate it I get the following error message:

Fatal error: Uncaught Error: Class "Redux_Extension_Abstract" not found in /home/kandprod/public_html/wp-content/plugins/redux-vendor-support-master/vendor_support/class-redux-extension-vendor-support.php:30 Stack trace: #0 /home/kandprod/public_html/wp-content/plugins/redux-vendor-support-master/redux-vendor-support.php(33): require() #1 /home/kandprod/public_html/wp-admin/includes/plugin.php(2314): include_once('/home/kandprod/...') #2 /home/kandprod/public_html/wp-admin/plugins.php(192): plugin_sandbox_scrape('redux-vendor-su...') #3 {main} thrown in /home/kandprod/public_html/wp-content/plugins/redux-vendor-support-master/vendor_support/class-redux-extension-vendor-support.php on line 30

I am trying to install it as it seems to be required for the theme MetaPortalVersion: 2.0.1 
By [Frenify](http://themeforest.net/user/frenify)

Is there anything i could do to resolve it?
Thank you in advance!

**Comment by IisusChristos** [comment]
Well, my bad... I installed the framwork and afterwards it worked.

**Comment by kprovance** [comment]
Yes, Redux Framework is what you need. This plugin is for developers who prefer not to use CDNs. It's not a consumer plugin. You can safely uninstall the vendor support plugin.
